### ISSUE TITLE
router.navigate trigger: false behaving oddly in child routers.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/history#2]
http://plnkr.co/edit/rlrl44myolUbvedl5Sit?p=preview

* Navigate to the Child Router.
  * Notice that the Activate Count is 2.
* Click the `Click Me!` button.
  * Notice that the Activate Count is 3
    * should be 2 since activate shouldn't have been called.
* Click the `Click Me!` button.
  * Notice that the Activate Count is 3
    * this is inconsistent with the previous click
* Click the `Welcome` nav button in the Child Router.
  * Notice that the Activate Count is 4
    * unclear if this is expected... seems like not since I am already on the welcome page
* Click the `Click Me!` button.
  * Notice that the Activate Count is 5
    * it seems that navigating away from the page and back resets it to the broken behavior

**Comment by EisenbergEffect** [comment]
@Zoltu I see that this issue is from a while back. Is the current version still causing a problem?

**Comment by EisenbergEffect** [comment]
Ok, I took a look. The reason you are seeing that behavior is that you actually have two different routes and you are switching back in forth between them, even though the map to the same module. As a result you get activations.

**Comment by Zoltu** [comment]
@EisenbergEffect Is there a workaround for this?

----

Note: I just re-read my instructions and I realized that you can better see the problem by clicking between the `Child Router` nav button and the `Click Me!` button.  If you click either of them twice in a row there is no counter bump.  If you alternate between them it bumps every time.

----

When I navigate to the route `child-router` it ends up routing to `child-router/welcome` due to that being the default route for `child-router`.  So the initial route is `child-router`, the final route is `child-router/welcome`.  Once on that page I then navigate to `welcome` from within `child-router` which will take me back to `child-router/welcome`.  This results in another activation.

Am I correct in understanding that activation depends on the original route rather than the final route?  This is unexpected behavior.  I would expect activation to depend on the final route, not the initial route.

The current behavior is problematic because the welcome page doesn't know about the full routing system, it only knows about its own route (welcome).  The fact that it is in a child router should be something that it shouldn't need to know anything about.  With the current behavior though, it seems I am forced to have my views know about the routing system which seems like a really bad pattern to fall into because it destroys isolation of components.

My real-world scenario is that the page needs to update the query string as the user interacts with the page so they can always get back to the current state they left at by just bookmarking the page or copying the URL.  In order to update the page, I am doing `this.router.navigate('this-view-name?${queryString}', { trigger: false })`.  Currently though, this causes activate to be called again *the first time the user touches the page* which currently has side effects that are problematic when the page is already activated.  After the first touch they can interact with the page without problem.
